import re
from datetime import date
from typing import Any, Generator, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from primaschema import METADATA_FILE_NAME, PRIMER_FILE_NAME, REFERENCE_FILE_NAME
from primaschema.schema.info import (
    PrimerSchemeChecksums,
    ConfiguredBaseModel,
    PrimerSchemeContributor,
    PrimerSchemeLicense,
    PrimerSchemeDevelopmentStatus,
    PrimerSchemeTargetOrganism,
)
from primaschema.schema.primer_scheme import PrimerScheme

# Mirrors PrimerScheme's own pattern_primer_scheme_name validator
# (src/primaschema/schema/info.py) - implemented as a field_validator rather
# than Field(pattern=...) because pydantic-core's native pattern matching
# compiles to Rust regex, which doesn't support the negative lookahead this
# pattern needs.
_PRIMER_SCHEME_NAME_PATTERN = re.compile(r"^(?!\.{1,2}$)[\da-z0-9_.-]+$")


class IndexPrimerScheme(BaseModel):
    """
    A subset of PrimerScheme for the index, with additional fields.
    """

    # Taken from PrimerScheme. name/version carry the same patterns as
    # PrimerScheme's own fields (not inherited - this is a separate model) so
    # a compromised/malicious index can't smuggle a path-traversal payload
    # (e.g. "..", or a "/"-containing value) through into the name/version
    # used to build local filesystem paths in get_scheme.py.
    primer_scheme_name: str = Field(
        default=...,
        description="""The name of the primer scheme used in an assay.""",
    )
    amplicon_size: int = Field(
        default=...,
        description="""The length of the amplicon generated by PCR amplification.""",
        ge=1,
    )
    primer_scheme_version: str = Field(
        default=...,
        description="""The version of the primer scheme.""",
        pattern=r"^v\d+\.\d+\.\d+(-[a-z0-9]+)?$",
    )
    primer_scheme_contributor: list[PrimerSchemeContributor] = Field(
        default=...,
        description="""Individuals, organisations, or institutions that have contributed to the development""",
    )
    primer_scheme_target_organism: list[PrimerSchemeTargetOrganism] = Field(
        default=...,
        description="""The organism against which this primer scheme is targeted. Lowercase, e.g. sars-cov-2""",
    )
    primer_scheme_license: PrimerSchemeLicense = Field(
        default=PrimerSchemeLicense.CC_BY_SA_4FULL_STOP0,
        description="""The license under which the primer scheme is distributed""",
    )
    primer_scheme_development_status: PrimerSchemeDevelopmentStatus = Field(
        default=...,
        description="""The status of the of the primer scheme in its development cycle.""",
    )
    primer_scheme_derived_from: Optional[str] = Field(
        default=None,
        description="""The original primer scheme from which the present scheme was derived.""",
    )
    checksums: Optional[PrimerSchemeChecksums] = Field(
        default=None,
        description="""SHA256 checksums for scheme files""",
    )
    primer_scheme_creation_date: Optional[date] = Field(
        default=None,
        description="""The date the primer scheme was created.""",
    )
    primer_scheme_submission_date: Optional[date] = Field(
        default=None,
        description="""The date the primer scheme was submitted to a repository.""",
    )
    base_url: str = Field(default="", exclude=True)  # Only used for URL synthesis
    primer_file_url: Optional[str] = Field(
        default=None,
        description="""URL to the primer.bed file""",
    )
    reference_file_url: Optional[str] = Field(
        default=None,
        description="""URL to the reference.fasta file""",
    )
    info_file_url: Optional[str] = Field(
        default=None,
        description="""URL to the info.json file""",
    )

    @field_validator("primer_scheme_name")
    @classmethod
    def _validate_primer_scheme_name(cls, v: str) -> str:
        if not _PRIMER_SCHEME_NAME_PATTERN.match(v):
            raise ValueError(f"Invalid primer_scheme_name format: {v}")
        return v

    # New fields
    @property
    def relative_path(self):
        return f"{self.primer_scheme_name}/{self.amplicon_size}/{self.primer_scheme_version}"

    @model_validator(mode="after")
    def _fill_urls(self):
        # Preserve URLs from JSON; only synthesize missing ones
        if not self.primer_file_url:
            if self.base_url:
                self.primer_file_url = (
                    f"{self.base_url}/{self.relative_path}/{PRIMER_FILE_NAME}"
                )
            else:
                self.primer_file_url = f"{self.relative_path}/{PRIMER_FILE_NAME}"
        if not self.reference_file_url:
            if self.base_url:
                self.reference_file_url = (
                    f"{self.base_url}/{self.relative_path}/{REFERENCE_FILE_NAME}"
                )
            else:
                self.reference_file_url = f"{self.relative_path}/{REFERENCE_FILE_NAME}"
        if not self.info_file_url:
            if self.base_url:
                self.info_file_url = (
                    f"{self.base_url}/{self.relative_path}/{METADATA_FILE_NAME}"
                )
            else:
                self.info_file_url = f"{self.relative_path}/{METADATA_FILE_NAME}"
        return self

    @classmethod
    def from_primer_scheme(
        cls, scheme: PrimerScheme, base_url: str = ""
    ) -> "IndexPrimerScheme":
        """Create an IndexPrimerScheme from a PrimerScheme instance."""
        return cls(
            primer_scheme_name=scheme.primer_scheme_name,
            amplicon_size=scheme.amplicon_size,
            primer_scheme_version=scheme.primer_scheme_version,
            primer_scheme_contributor=scheme.primer_scheme_contributor,
            primer_scheme_target_organism=scheme.primer_scheme_target_organism,
            primer_scheme_license=scheme.primer_scheme_license
            or PrimerSchemeLicense.CC_BY_SA_4FULL_STOP0,
            primer_scheme_development_status=scheme.primer_scheme_development_status,
            primer_scheme_derived_from=scheme.primer_scheme_derived_from,
            checksums=scheme.checksums,
            primer_scheme_creation_date=scheme.primer_scheme_creation_date,
            primer_scheme_submission_date=scheme.primer_scheme_submission_date,
            base_url=base_url,
        )


class PrimerSchemeIndex(ConfiguredBaseModel):
    """
    An index of primer schemes.
    """

    primerschemes: dict[str, dict[int, dict[str, IndexPrimerScheme]]] = Field(
        default_factory=dict,
        description="Index of primer schemes structured as {name: {amplicon_size: {version: scheme}}}",
    )

    def flatten(self, data: Optional[Any] = None) -> list[IndexPrimerScheme]:
        """
        Recursively flattens values from any level of the dictionary.
        If no data is provided, flattens the entire primerschemes dict.
        """
        return list(
            self._yield_schemes(data if data is not None else self.primerschemes)
        )

    def _yield_schemes(self, data: Any) -> Generator[IndexPrimerScheme, None, None]:
        """Recursive generator to find IndexPrimerScheme leaves."""
        if isinstance(data, IndexPrimerScheme):
            yield data
        elif isinstance(data, dict):
            for value in data.values():
                yield from self._yield_schemes(value)
        elif isinstance(data, list):
            for item in data:
                yield from self._yield_schemes(item)

    def get_schemes_from_index(
        self,
        name: str,
        amplicon_size: Optional[int | str] = None,
        version: Optional[str] = None,
    ) -> list[IndexPrimerScheme]:
        """
        Returns all schemes matching the provided criteria.

        Raises:
            ValueError: If an entry's own fields disagree with the dict keys
                (name/amplicon_size/version) it was filed under - this can
                only happen with a hand-crafted or corrupted index JSON,
                since add_index_primer_scheme() always files an entry under
                keys derived from that same entry's fields.
        """
        name_level = self.primerschemes.get(name, {})

        if amplicon_size:
            amplicon_size = int(amplicon_size)
            amplicon_size_level = name_level.get(amplicon_size, {})
            if version:
                entry = amplicon_size_level.get(version)
                schemes = [entry] if entry is not None else []
            else:
                schemes = self.flatten(amplicon_size_level)
        else:
            schemes = self.flatten(name_level)

        for scheme in schemes:
            if scheme.primer_scheme_name != name:
                raise ValueError(
                    f"Corrupted index: entry filed under name {name!r} has "
                    f"primer_scheme_name={scheme.primer_scheme_name!r}"
                )
            if amplicon_size and scheme.amplicon_size != amplicon_size:
                raise ValueError(
                    f"Corrupted index: entry filed under amplicon_size "
                    f"{amplicon_size!r} has amplicon_size={scheme.amplicon_size!r}"
                )
            if version and scheme.primer_scheme_version != version:
                raise ValueError(
                    f"Corrupted index: entry filed under version {version!r} "
                    f"has primer_scheme_version={scheme.primer_scheme_version!r}"
                )

        return schemes

    def add_index_primer_scheme(self, index: IndexPrimerScheme, strict=True):
        # Get or create the substructure
        name_level = self.primerschemes.setdefault(index.primer_scheme_name, {})
        amplicon_size_level = name_level.setdefault(index.amplicon_size, {})

        # If the version already exists, check hashes are consistent if strict
        if index.primer_scheme_version in amplicon_size_level and strict:
            original = amplicon_size_level[index.primer_scheme_version]

            if original.checksums != index.checksums:
                raise ValueError(
                    f"checksums have changed for {index.relative_path}. Use Strict == False to allow."
                )

            # If file hashes match update entry.
            amplicon_size_level[index.primer_scheme_version] = index
        else:
            # new scheme
            amplicon_size_level[index.primer_scheme_version] = index

    def remove_index_primer_scheme(self, index: IndexPrimerScheme) -> bool:
        # Early return if not present
        name_level = self.primerschemes.get(index.primer_scheme_name)
        if name_level is None:
            return False

        amplicon_size_level = name_level.get(index.amplicon_size)
        if amplicon_size_level is None:
            return False

        if index.primer_scheme_version in amplicon_size_level:
            amplicon_size_level.pop(index.primer_scheme_version)
            # Prune the tree
            self.prune_index()  # if this is common could do a targeted prune
            return True
        return False

    def prune_index(self):
        """Removes any empty stems"""
        # Iterate over a copy of keys to allow modification during iteration
        for name in list(self.primerschemes.keys()):
            name_level = self.primerschemes[name]

            for amplicon_size in list(name_level.keys()):
                amplicon_size_level = name_level[amplicon_size]

                # If the version dict is empty, remove the amplicon_size key
                if not amplicon_size_level:
                    del name_level[amplicon_size]

            # If the name dict is empty, remove the name key
            if not name_level:
                del self.primerschemes[name]


def create_index(
    primer_schemes: list[PrimerScheme], base_url: str = ""
) -> PrimerSchemeIndex:
    psi = PrimerSchemeIndex()

    for ps in primer_schemes:
        # Convert to index entry
        mps = IndexPrimerScheme.from_primer_scheme(ps, base_url=base_url)
        psi.add_index_primer_scheme(mps)
    return psi


def update_index(
    primer_schemes: list[PrimerScheme],
    index: PrimerSchemeIndex,
    strict: bool = True,
    base_url: str = "",
):
    for ps in primer_schemes:
        # Convert to index entry
        mps = IndexPrimerScheme.from_primer_scheme(ps, base_url=base_url)
        index.add_index_primer_scheme(mps, strict)
